export const MOCK_CITIES = {
  // === Assam (35) ===
  'Kamrup Metropolitan': ['Guwahati', 'Dispur', 'Sonapur', 'Chandrapur', 'Azara'],
  'Kamrup': ['Rangia', 'Palashbari', 'Hajo', 'Boko', 'Chhaygaon', 'Goreswar'],
  'Dibrugarh': ['Dibrugarh', 'Chabua', 'Duliajan', 'Naharkatia', 'Tingkhong', 'Moran'],
  'Silchar': ['Silchar', 'Lakhipur', 'Sonai', 'Udarbond', 'Borkhola'],
  'Cachar': ['Silchar', 'Lakhipur', 'Sonai', 'Udarbond', 'Borkhola'],
  'Jorhat': ['Jorhat', 'Titabor', 'Teok', 'Majuli', 'Mariani'],
  'Nagaon': ['Nagaon', 'Kaliabor', 'Hojai', 'Raha', 'Kampur', 'Lumding'],
  'Sonitpur': ['Tezpur', 'Dhekiajuli', 'Biswanath Chariali', 'Gohpur', 'Rangapara'],
  'Tinsukia': ['Tinsukia', 'Digboi', 'Margherita', 'Doomdooma', 'Sadiya'],
  'Golaghat': ['Golaghat', 'Bokakhat', 'Dergaon', 'Sarupathar', 'Khumtai'],
  'Sivasagar': ['Sivasagar', 'Nazira', 'Amguri', 'Demow', 'Sonari'],
  'Barpeta': ['Barpeta', 'Howly', 'Barpeta Road', 'Sarthebari', 'Kalgachia'],
  'Dhubri': ['Dhubri', 'Gauripur', 'Bilasipara', 'Golakganj', 'Mankachar'],
  'Bongaigaon': ['Bongaigaon', 'Abhayapuri', 'Bijni'],
  'Baksa': ['Mushalpur', 'Tamulpur', 'Salbari', 'Goreswar'],
  'Bajali': ['Pathsala', 'Bhabanipur', 'Patacharkuchi'],
  'Biswanath': ['Biswanath Chariali', 'Gohpur', 'Halem'],
  'Charaideo': ['Sonari', 'Mahmora', 'Sapekhati'],
  'Chirang': ['Kajalgaon', 'Bijni', 'Basugaon'],
  'Darrang': ['Mangaldoi', 'Sipajhar', 'Dalgaon', 'Kharupetia'],
  'Dhemaji': ['Dhemaji', 'Jonai', 'Silapathar', 'Gogamukh'],
  'Dima Hasao': ['Haflong', 'Maibang', 'Umrangso', 'Mahur'],
  'Goalpara': ['Goalpara', 'Dudhnoi', 'Lakhipur', 'Mornoi'],
  'Hailakandi': ['Hailakandi', 'Algapur', 'Lala', 'Katlicherra'],
  'Hojai': ['Hojai', 'Lanka', 'Lumding', 'Doboka'],
  'Karbi Anglong': ['Diphu', 'Bokajan', 'Howraghat', 'Manja'],
  'Karimganj': ['Karimganj', 'Badarpur', 'Patherkandi', 'Ramkrishna Nagar'],
  'Kokrajhar': ['Kokrajhar', 'Gossaigaon', 'Fakiragram', 'Dotma'],
  'Lakhimpur': ['North Lakhimpur', 'Bihpuria', 'Narayanpur', 'Dhakuakhana'],
  'Majuli': ['Garamur', 'Kamalabari', 'Jengraimukh'],
  'Morigaon': ['Morigaon', 'Jagiroad', 'Bhuragaon', 'Laharijan'],
  'Nalbari': ['Nalbari', 'Tihu', 'Mukalmua', 'Belsor'],
  'South Salmara-Mankachar': ['Hatsingimari', 'Mankachar', 'South Salmara'],
  'Udalguri': ['Udalguri', 'Tangla', 'Kalaigaon', 'Mazbat'],
  'West Karbi Anglong': ['Hamren', 'Baithalangso', 'Donkamokam'],

  // === Arunachal Pradesh (21) ===
  'Tawang': ['Tawang Town', 'Lumla', 'Jang'],
  'West Kameng': ['Bomdila', 'Dirang', 'Kalaktang', 'Rupa', 'Bhalukpong'],
  'East Kameng': ['Seppa', 'Chayangtajo', 'Bameng'],
  'Papum Pare': ['Itanagar', 'Naharlagun', 'Yupia', 'Sagalee', 'Kimin'],
  'Kurung Kumey': ['Koloriang', 'Nyapin', 'Palin'],
  'Kra Daadi': ['Jamin', 'Palin'],
  'Lower Subansiri': ['Ziro', 'Hapoli', 'Yachuli'],
  'Upper Subansiri': ['Daporijo', 'Dumporijo', 'Taliha'],
  'West Siang': ['Aalo', 'Basar', 'Mechuka', 'Likabali'],
  'East Siang': ['Pasighat', 'Ruksin', 'Mebo'],
  'Siang': ['Pangin', 'Boleng'],
  'Upper Siang': ['Yingkiong', 'Tuting', 'Mariyang'],
  'Lower Siang': ['Likabali', 'Nari'],
  'Lower Dibang Valley': ['Roing', 'Dambuk'],
  'Dibang Valley': ['Anini', 'Etalin'],
  'Anjaw': ['Hawai', 'Hayuliang', 'Walong'],
  'Lohit': ['Tezu', 'Wakro', 'Sunpura'],
  'Namsai': ['Namsai', 'Chowkham', 'Lekang'],
  'Changlang': ['Changlang', 'Miao', 'Bordumsa', 'Khonsa', 'Jairampur'],
  'Tirap': ['Khonsa', 'Deomali', 'Lazu'],
  'Longding': ['Longding', 'Kanubari', 'Pangchau'],

  // === Manipur (16) ===
  'Bishnupur': ['Bishnupur', 'Moirang', 'Nambol'],
  'Chandel': ['Chandel', 'Tengnoupal', 'Moreh'],
  'Churachandpur': ['Churachandpur', 'Tuibong', 'Singngat'],
  'Imphal East': ['Porompat', 'Jiribam', 'Keirao Bitra'],
  'Imphal West': ['Lamphelpat', 'Lamsang', 'Patsoi'],
  'Jiribam': ['Jiribam', 'Borobekra'],
  'Kakching': ['Kakching', 'Waikhong', 'Sugnu'],
  'Kamjong': ['Kamjong', 'Kasom Khullen', 'Phungyar'],
  'Kangpokpi': ['Kangpokpi', 'Saitu', 'Saikul'],
  'Noney': ['Noney', 'Khoupum', 'Haochong'],
  'Pherzawl': ['Pherzawl', 'Parbung', 'Thanlon'],
  'Senapati': ['Senapati', 'Mao', 'Tadubi'],
  'Tamenglong': ['Tamenglong', 'Tousem', 'Tamei'],
  'Tengnoupal': ['Tengnoupal', 'Machi', 'Moreh'],
  'Thoubal': ['Thoubal', 'Lilong', 'Yairipok'],
  'Ukhrul': ['Ukhrul', 'Jessami', 'Chingai'],

  // === Meghalaya (11) ===
  'East Garo Hills': ['Williamnagar', 'Rongjeng', 'Songsak'],
  'East Jaintia Hills': ['Khliehriat', 'Saipung'],
  'East Khasi Hills': ['Shillong', 'Sohra (Cherrapunji)', 'Pynursla', 'Mawsynram'],
  'North Garo Hills': ['Resubelpara', 'Bajengdoba'],
  'Ri Bhoi': ['Nongpoh', 'Umsning', 'Jirang'],
  'South Garo Hills': ['Baghmara', 'Chokpot'],
  'South West Garo Hills': ['Ampati', 'Betasing'],
  'South West Khasi Hills': ['Mawkyrwat', 'Ranikor'],
  'West Garo Hills': ['Tura', 'Dadenggre', 'Garobadha'],
  'West Jaintia Hills': ['Jowai', 'Amlarem'],
  'West Khasi Hills': ['Nongstoin', 'Mairang'],

  // === Mizoram (8) ===
  'Aizawl': ['Aizawl', 'Darlawn', 'Saitual'],
  'Champhai': ['Champhai', 'Khawzawl', 'Ngopa'],
  'Kolasib': ['Kolasib', 'Vairengte', 'Bairabi'],
  'Lawngtlai': ['Lawngtlai', 'Chawngte'],
  'Lunglei': ['Lunglei', 'Tlabung', 'Hnahthial'],
  'Mamit': ['Mamit', 'Kawrthah', 'Reiek'],
  'Saiha': ['Saiha', 'Tuipang'],
  'Serchhip': ['Serchhip', 'North Vanlaiphai', 'Thenzawl'],

  // === Nagaland (11) ===
  'Dimapur': ['Dimapur', 'Chumukedima', 'Medziphema'],
  'Kiphire': ['Kiphire', 'Pungro', 'Seyochung'],
  'Kohima': ['Kohima', 'Jakhama', 'Tseminyu'],
  'Longleng': ['Longleng', 'Tamlu'],
  'Mokokchung': ['Mokokchung', 'Tuli', 'Mangkolemba'],
  'Mon': ['Mon', 'Tizit', 'Naginimora'],
  'Peren': ['Peren', 'Jalukie', 'Tening'],
  'Phek': ['Phek', 'Pfütsero', 'Meluri'],
  'Tuensang': ['Tuensang', 'Noklak', 'Shamator'],
  'Wokha': ['Wokha', 'Bhandari', 'Sanis'],
  'Zunheboto': ['Zunheboto', 'Aghunato', 'Satakha'],

  // === Sikkim (4) ===
  'East Sikkim': ['Gangtok', 'Singtam', 'Rangpo'],
  'North Sikkim': ['Mangan', 'Chungthang', 'Lachen', 'Lachung'],
  'South Sikkim': ['Namchi', 'Ravangla', 'Jorethang'],
  'West Sikkim': ['Gyalshing', 'Soreng', 'Pelling'],

  // === Tripura (8) ===
  'Dhalai': ['Ambassa', 'Kamalpur', 'Longtharai Valley'],
  'Gomati': ['Udaipur', 'Amarpur', 'Karbook'],
  'Khowai': ['Khowai', 'Teliamura'],
  'North Tripura': ['Dharmanagar', 'Kanchanpur', 'Panisagar'],
  'Sepahijala': ['Bishramganj', 'Sonamura', 'Jampuijala'],
  'South Tripura': ['Belonia', 'Sabroom', 'Santirbazar'],
  'Unakoti': ['Kailashahar', 'Kumarghat'],
  'West Tripura': ['Agartala', 'Jirania', 'Mohanpur']
};

export const MOCK_WARDS = {
  // Select generic realistic wards/localities based on city
  'Guwahati': ['Panbazar (Ward 1)', 'Uzanbazar (Ward 2)', 'Silpukhuri (Ward 3)', 'Paltan Bazar (Ward 4)', 'Ulubari (Ward 5)', 'Ganeshguri (Ward 6)', 'Beltola (Ward 7)'],
  'Dispur': ['Secretariat Area', 'Ganeshguri', 'Supermarket', 'Six Mile'],
  'Agartala': ['Banamalipur (Ward 10)', 'Indranagar (Ward 11)', 'Joynagar (Ward 12)', 'Shivnagar (Ward 13)'],
  'Shillong': ['Police Bazar', 'Laitumkhrah', 'Mawlai', 'Nongthymmai', 'Laban'],
  'Dibrugarh': ['Chowkidinghee', 'Khaliamari', 'Boiragimoth', 'Amolapatty', 'Santipara'],
  'Silchar': ['Tarapur', 'Malugram', 'Itkhola', 'Ambikapatty', 'Meherpur'],
  'Jorhat': ['Borbheta', 'Tarajan', 'Choladhara', 'Cinnamara', 'Mariani Road'],
  'Tezpur': ['Mahabhairab', 'Mazgaon', 'Dekargaon', 'Mission Chariali'],
  'Tinsukia': ['Makum Road', 'Hijuguri', 'Tinsukia Town', 'Doomdooma Road'],
  'Nagaon': ['Haibargaon', 'Fouzdaripatty', 'Dimaruguri', 'Itachali'],
  'Itanagar': ['Gohpur Tinali', 'Niti Vihar', 'Bank Tinali', 'Chandranagar'],
  'Aizawl': ['Bawngkawn', 'Chanmari', 'Zarkawt', 'Mission Veng', 'Khatla'],
  'Kohima': ['PR Hill', 'High School Area', 'Keziekie', 'Lerie'],
  'Dimapur': ['Duncan Basti', 'Circular Road', 'Purana Bazar', 'Walford'],
  'Gangtok': ['MG Marg', 'Tibet Road', 'Development Area', 'Deorali'],
  'Tawang Town': ['Old Market', 'New Market', 'Monastery Area'],
};

// Fallback logic inside SetupScreen will generate "Ward 1, Ward 2" etc. if the specific city is not mapped.
